services:
  clickhouse-server:
    # CORRECTED: Use the official 'clickhouse' image with a stable LTS tag.
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server

    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client interface
    volumes:
      # This persists our database data on our local machine.
      - ./clickhouse_data:/var/lib/clickhouse/
      # This makes our local CSVs available inside the container.
      - ./sample_data:/var/lib/clickhouse/user_files
      # mount SQL to run them via client
      - ./sql:/sql
    # Best practice from official docs to prevent "too many open files" errors.
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

